export default function handler(req, res) {
  const prompts = {
    "animal": [
      "wolf", "lion", "tiger", "bear", "fox", "owl", "eagle", "panther", "raven", "bat",
      "deer", "shark", "dolphin", "whale", "cat", "dog", "lizard", "gecko", "spider", "jellyfish",
      "crab", "octopus", "kangaroo", "sloth", "elephant", "giraffe", "penguin", "zebra", "skunk", "raccoon",
      "hedgehog", "armadillo", "toucan", "parrot", "vulture", "hyena", "cobra", "python", "rabbit", "boar",
      "snail", "ant", "bee", "stingray", "piranha", "crocodile", "frog", "tortoise", "flamingo", "peacock",
      "beetle", "butterfly", "moth", "mouse", "rat", "ferret", "llama", "yak", "ox", "bull",
      "horse", "donkey", "newt", "salamander", "tiger shark", "leopard", "cheetah", "chameleon", "koala", "porcupine",
      "platypus", "starfish", "swan", "weasel", "badger", "mongoose", "scorpion", "termite", "firefly", "dragonfly",
      "locust", "ibis", "bison", "mole", "jackal", "lynx", "stoat", "geese", "turkey", "macaw",
      "caracal", "wolverine", "capybara", "dugong", "narwhal", "manatee", "civet", "quokka", "pangolin", "cassowary",
      "gibbon", "tapir", "okapi", "aye-aye", "tarsier", "bandicoot", "echidna", "sifaka", "margay", "genet",
      "serval", "binturong", "saola", "markhor", "kinkajou", "coati", "agouti", "guenon", "dhole", "bushbaby",
      "zorilla", "fossa", "jerboa", "paca", "dik-dik", "springbok", "eland", "duiker", "hartebeest", "grison",
      "takin", "nilgai", "kudu", "galago", "klipspringer", "goral", "ibex", "muskox", "vicuna", "guanaco",
      "maned wolf", "andrew's beaked whale", "frilled lizard", "leaf-tailed gecko", "glaucus atlanticus", "nudibranch", "basket star", "sea cucumber", "blobfish", "gulper eel",
      "vampire squid", "glass frog", "axolotl", "hellbender", "olm", "caecilian", "thorny devil", "gila monster", "komodo dragon", "marine iguana",
      "tuatara", "sawfish", "goblin shark", "wobbegong", "cookiecutter shark", "anglerfish", "hatchetfish", "flashlight fish", "lanternfish", "viperfish",
      "barreleye", "tripod fish", "oarfish", "giant isopod", "mimic octopus", "blue ringed octopus", "nautilus", "cone snail", "pistol shrimp", "mantis shrimp",
      "stonefish", "lionfish", "sea dragon", "leafy sea dragon", "seahorse", "coral grouper", "moray eel", "fire coral", "brain coral", "staghorn coral",
      "box jellyfish", "Portuguese man o' war", "moon jellyfish", "sea nettle", "sea anemone", "nudibranch", "cuttlefish", "pearlfish", "remora", "pilot fish",
      "humboldt squid", "bobtail squid", "giant clam", "triton snail", "cowfish", "pufferfish", "triggerfish", "filefish", "porcupinefish", "parrotfish",
      "wrasse", "goby", "blenny", "jawfish", "eel catfish", "catshark", "bamboo shark", "nurse shark", "thresher shark", "mako shark",
      "hammerhead shark", "reef shark", "tigerfish", "goliath tigerfish", "arapaima", "electric eel", "pacu", "oscar", "discus", "clown loach",
      "koi", "goldfish", "betta", "guppy", "platy", "swordtail", "angelfish", "tetra", "danio", "barb",
      "corydoras", "pleco", "hillstream loach", "mudskipper", "lungfish", "bichir", "knifefish", "glass catfish", "rainbowfish", "butterfly fish"
    ],
    "medium": [
      "digital", "ink", "pencil", "charcoal", "watercolor", "acrylic", "oil paint", "vector", "pixel", "marker",
      "chalk", "pastel", "graffiti", "spray paint", "linocut", "woodblock", "collage", "mixed media", "3D model", "papercut",
      "sculpture", "clay", "bronze", "marble", "sand", "snow", "fabric", "embroidery", "needlepoint", "crayon",
      "calligraphy", "tattoo flash", "body paint", "airbrush", "stop motion", "scratchboard", "stained glass", "tempera", "encaustic", "foil",
      "quilling", "origami", "crochet", "knit", "drip paint", "splatter", "hyperrealism", "flat design", "line art", "comic style",
      "manga", "anime", "storybook", "expressionist", "cubist", "impressionist", "realism", "surrealism", "steampunk", "cyberpunk"
    ],
    "genre": [
      "fantasy", "sci-fi", "horror", "noir", "surreal", "abstract", "post-apocalyptic", "utopian", "dystopian", "space opera",
      "mecha", "bio-punk", "steampunk", "cyberpunk", "urban fantasy", "high fantasy", "low fantasy", "magical realism", "grimdark", "occult",
      "mythology", "fairy tale", "historical fiction", "kaiju", "dreamcore", "weirdcore", "slice of life", "comedy", "dark comedy", "supernatural",
      "ghost story", "gothic", "zombie apocalypse", "creature feature", "silent film", "spy thriller", "romance", "tragedy", "satire", "mockumentary",
      "wild west", "feudal Japan", "modern day", "futuristic", "ancient world", "court drama", "detective noir", "time travel", "parallel world", "cosmic horror"
    ],
   "character": [
      "knight", "wizard", "witch", "robot", "cyborg", "android", "ghost", "vampire", "werewolf", "druid",
      "ranger", "hunter", "assassin", "thief", "bard", "sorcerer", "necromancer", "shapeshifter", "pirate", "samurai",
      "ninja", "cowboy", "gunslinger", "space marine", "alien", "mutant", "superhero", "villain", "healer", "alchemist",
      "scientist", "engineer", "hacker", "spy", "detective", "priest", "monk", "cultist", "prince", "princess",
      "king", "queen", "emperor", "empress", "gladiator", "brawler", "swordsman", "archer", "sniper", "telepath",
      "fire mage", "ice mage", "battle nun", "spirit medium", "dreamwalker", "clone", "lucid dreamer", "android monk", "puppetmaster", "trickster",
      "time traveler", "beast tamer", "blood mage", "plague doctor", "rune carver", "bone collector", "demon slayer", "soul reaper", "revolutionary", "oracle",
      "stormcaller", "chrono-mancer", "memory thief", "mirror walker", "dimension hopper", "cyber priest", "data ghost", "astral knight", "starborn child", "void walker",
      "junkyard mechanic", "hologram assassin", "mutant prophet", "feral child", "dreamsmith", "sand mage", "cursed poet", "street magician", "vampire hunter", "zombie warlord",
      "wasteland king", "gravity shifter", "nanite swarmlord", "plasma sniper", "energy bender", "cosmic monk", "neon drifter", "symbiote host", "ancient automaton", "arcane engineer",
      "crystal golem", "eldritch scholar", "fog dancer", "phantom thief", "insect queen", "corpse puppeteer", "witch hunter", "ghoul", "sandwalker", "sky pirate",
      "flesh crafter", "shadow forger", "bounty priest", "alien diplomat", "biohacker", "solar paladin", "moon priestess", "toxin alchemist", "storm shaman", "relic hunter"
    ],
    "lighting": [
      "harsh spotlight", "neon glow", "warm sunset", "cool moonlight", "studio lighting", "candlelight", "backlit", "rim light", "top-down", "underlit",
      "silhouetted", "glowing outline", "overexposed", "no lighting", "dramatic contrast", "foggy ambiance", "blinding sunlight", "ambient lighting", "low light", "flickering flame"
    ],
    "vibe": [
      "eerie", "peaceful", "chaotic", "dreamy", "surreal", "whimsical", "ominous", "tense", "romantic", "serene",
      "cold", "warm", "nostalgic", "epic", "intimate", "cinematic", "claustrophobic", "open", "spiritual", "punk"
    ],
    "emotion": [
      "anger", "joy", "fear", "sadness", "excitement", "boredom", "awe", "confusion", "hope", "despair",
      "rage", "melancholy", "delight", "shock", "panic", "relief", "determination", "peace", "envy", "pride"
    ],
    "color": [
      "monochrome", "complementary", "analogous", "neon", "pastel", "vibrant", "earth tones", "grayscale", "primary colors", "cool palette",
      "warm palette", "red dominant", "blue dominant", "green dominant", "purple hues", "orange tones", "black & white", "sepia", "muted colors", "saturated colors"
    ],
    "camera": [
      "wide angle", "close-up", "extreme close-up", "low angle", "high angle", "top-down", "over-the-shoulder", "dutch tilt", "zoomed in", "zoomed out",
      "fish-eye", "drone shot", "crane shot", "tracking shot", "first-person view", "third-person", "POV", "static shot", "panning", "slow motion"
    ],
    "franchiseCharacter": [
    "Spider-Man", "Miles Morales", "Superman", "Batman", "Wonder Woman", "The Flash", "Black Panther", "Storm", "Static Shock", "Iron Man",
    "Captain America", "Blade", "Green Lantern (John Stewart)", "Cyborg", "Shuri", "Luke Cage", "Misty Knight", "Falcon", "Ironheart",
    "Blue Beetle", "Nova", "Doctor Doom", "Magneto", "Mystique", "Scarlet Witch", "Vision", "Moon Knight", "Daredevil", "Punisher",
    "Deadpool", "Peacemaker", "Harley Quinn", "Poison Ivy", "Joker", "Vixen", "Batwing", "Goku", "Vegeta", "Piccolo", "Spike Spiegel",
    "Kamina", "Simon", "Yoruichi Shihōin", "Afro Samurai", "Ichigo Kurosaki", "Naruto", "Sasuke", "Sailor Moon", "Luffy", "Zoro",
    "Nico Robin", "Eren Yeager", "Levi Ackerman", "Mikasa", "Ryuko Matoi", "Mob", "Tengen Uzui", "Gojo", "Yusuke Urameshi",
    "Killua", "Gon", "Nezuko", "Tanjiro", "America Chavez", "Monica Rambeau", "Riri Williams", "Kamala Khan", "Echo (Maya Lopez)",
    "Warpath", "Forge", "Bishop", "Agent 355", "Amanda Waller", "Okoye", "Nakia", "Zaya the Desert Blade", "Raheem the Chrono-Paladin",
    "Kaori the Flame Whisperer", "Tariq the Dream Hacker", "Selene the Bone Oracle", "Ahsoka", "Darth Vader", "Bo-Katan", "Kylo Ren",
    "Thanos", "Galactus", "Loki", "Hela", "Carnage", "Venom", "Spawn", "Hellboy", "Aang", "Korra", "Toph", "Zuko", "She-Ra", "He-Man",
    "Ben 10", "Invincible", "Omni-Man", "Doctor Fate", "Zatanna", "Rogue", "Gambit", "Wolverine", "Black Canary", "Hawkman",
    "Shang-Chi", "Jessica Jones", "Kate Bishop", "Echo", "White Tiger", "Namor", "Namora", "Cassandra Cain", "Stephanie Brown", "Red Hood",
    "Nightwing", "Beast Boy", "Raven", "Starfire", "Cyborg Superman", "Terra", "Blue Marvel", "Hercules (Marvel)", "Wonder Man", "Moon Girl",
    "Devil Dinosaur", "Big Hero 6", "Baymax", "Hiro Hamada", "Wasabi", "Honey Lemon", "Fredzilla", "Silk", "Cloak", "Dagger",
    "X-23", "Laura Kinney", "Armor", "Marrow", "Boom-Boom", "Jubilee", "Pixie", "Dust", "Elixir", "Prodigy",
    "Quicksilver", "Polaris", "Northstar", "Aurora", "Havok", "Banshee", "Siryn", "Multiple Man", "Strong Guy",
    "Domino", "Cable", "Feral", "Shatterstar", "Rictor", "Blindfold", "Legion", "Moira MacTaggert", "Omega Red",
    "Sabretooth", "Destiny", "Madelyne Pryor", "Hope Summers", "Franklin Richards", "Valeria Richards", "Molecule Man", "Uatu the Watcher", "Silver Surfer",
    "Black Bolt", "Medusa", "Karnak", "Crystal", "Lockjaw", "Maximus", "Beta Ray Bill", "Nova (Richard Rider)", "Star-Lord", "Gamora",
    "Drax", "Rocket Raccoon", "Groot", "Mantis", "Yondu", "Nebula", "The Collector", "Grandmaster", "Adam Warlock", "High Evolutionary",
    "Ghost Rider (Johnny Blaze)", "Ghost Rider (Robbie Reyes)", "Morbius", "Man-Thing", "Werewolf by Night", "Elsa Bloodstone", "Howard the Duck", "Moon-Boy",
    "Saitama", "Genos", "Tatsumaki", "King", "Fubuki", "Speed-o'-Sound Sonic", "Mumen Rider", "Garou", "Bang", "Atomic Samurai",
    "Kenshin Himura", "Sanosuke Sagara", "Misao Makimachi", "Shishio Makoto", "Yukishiro Enishi", "Edward Elric", "Alphonse Elric", "Roy Mustang", "Riza Hawkeye", "Scar",
    "Gintoki Sakata", "Kagura", "Shinpachi Shimura", "Hijikata Toshiro", "Okita Sougo", "Lelouch Lamperouge", "Suzaku Kururugi", "C.C.", "Kallen Stadtfeld", "Jeremiah Gottwald",
    "Joel Miller", "Ellie Williams", "Abby Anderson", "Tommy Miller", "Dina", "Lev", "Jesse", "Marlene", "Tess", "Sarah Miller",
    "Kratos", "Atreus", "Zeus (God of War)", "Baldur", "Freya", "Thor (God of War)", "Odin (God of War)", "Heimdall", "Faye", "Sigrun",
    "Link", "Zelda", "Ganondorf", "Midna", "Impa", "Tingle", "Skull Kid", "Revali", "Daruk", "Mipha",
    "Cloud Strife", "Tifa Lockhart", "Aerith Gainsborough", "Barret Wallace", "Red XIII", "Sephiroth", "Vincent Valentine", "Yuffie Kisaragi", "Zack Fair", "Reno",
    "Squall Leonhart", "Rinoa Heartilly", "Laguna Loire", "Seifer Almasy", "Quistis Trepe", "Selphie Tilmitt", "Irvine Kinneas", "Ultimecia", "Edea Kramer", "Zell Dincht",
    "Tidus", "Yuna", "Auron", "Lulu", "Wakka", "Kimahri", "Rikku", "Seymour Guado", "Jecht", "Braska",
    "Sora", "Riku", "Kairi", "Roxas", "Axel", "Xion", "Ventus", "Terra", "Aqua", "Master Xehanort",
    "Kirby", "Meta Knight", "King Dedede", "Waddle Dee", "Bandana Dee", "Marx", "Magolor", "Gooey", "Dark Meta Knight", "Galacta Knight",
    "Samus Aran", "Ridley", "Dark Samus", "Mother Brain", "Kraid", "Adam Malkovich", "Sylux", "Rundas", "Gandrayda", "Dark Samus (Phazon)",
    "Donkey Kong", "Diddy Kong", "Dixie Kong", "Funky Kong", "Cranky Kong", "King K. Rool", "Tiny Kong", "Lanky Kong", "Chunky Kong", "Wrinkly Kong",
    "Fox McCloud", "Falco Lombardi", "Peppy Hare", "Slippy Toad", "Wolf O'Donnell", "Krystal", "Leon Powalski", "Andrew Oikonny", "Pigma Dengar", "James McCloud",
    "Sam Fisher", "Lara Croft", "Nathan Drake", "Chloe Frazer", "Victor Sullivan", "Elena Fisher", "Rafe Adler", "Nadine Ross", "Cassandra Morgan", "Harry Flynn",
    "Ezio Auditore", "Altair Ibn-La'Ahad", "Connor Kenway", "Edward Kenway", "Bayek of Siwa", "Kassandra", "Eivor Varinsdottir", "Desmond Miles", "Layla Hassan", "Basim",
    "Geralt of Rivia", "Yennefer of Vengerberg", "Ciri", "Triss Merigold", "Dandelion", "Vesemir", "Lambert", "Eskel", "Emhyr var Emreis", "Gaunter O'Dimm",
    "Harry Potter", "Hermione Granger", "Ron Weasley", "Albus Dumbledore", "Severus Snape", "Draco Malfoy", "Voldemort", "Sirius Black", "Remus Lupin", "Bellatrix Lestrange",
    "Bilbo Baggins", "Frodo Baggins", "Samwise Gamgee", "Gandalf", "Aragorn", "Legolas", "Gimli", "Boromir", "Galadriel", "Sauron",
    "Percy Jackson", "Annabeth Chase", "Grover Underwood", "Luke Castellan", "Thalia Grace", "Nico di Angelo", "Clarisse La Rue", "Tyson", "Chiron", "Hades",
    "Katniss Everdeen", "Peeta Mellark", "Gale Hawthorne", "Effie Trinket", "Haymitch Abernathy", "President Snow", "Finnick Odair", "Johanna Mason", "Rue", "Primrose Everdeen",
    "Ender Wiggin", "Valentine Wiggin", "Peter Wiggin", "Bean", "Petra Arkanian", "Mazer Rackham", "Alai", "Bonzo Madrid", "Colonel Graff", "Dink Meeker",
    "Light Yagami", "L", "Ryuk", "Misa Amane", "Near", "Mello", "Watari", "Soichiro Yagami", "Teru Mikami",
    "Kaneki Ken", "Touka Kirishima", "Rize Kamishiro", "Amon Koutarou", "Juuzou Suzuya", "Shuu Tsukiyama", "Uta", "Yoshimura", "Hinami Fueguchi", "Arima Kishou",
    "Shinichi Izumi", "Migi", "Kana Kimishima", "Satomi Murano", "Hirokawa", "Gotou", "Tamura Reiko", "Urano", "Yamagishi", "Kurumada",
    "Yuji Itadori", "Megumi Fushiguro", "Nobara Kugisaki", "Satoru Gojo", "Suguru Geto", "Toji Fushiguro", "Kento Nanami", "Mahito", "Choso", "Maki Zenin",
    "Samurai Jack", "Aku", "Dexter", "Dee Dee", "Johnny Bravo", "Courage the Cowardly Dog", "Eustace", "Muriel", "Ed", "Edd",
    "Eddy", "Blossom", "Bubbles", "Buttercup", "Professor Utonium", "Mojo Jojo", "Ben Tennyson", "Gwen Tennyson", "Kevin Levin", "Vilgax",
    "Robin", "Slade", "Aqualad", "Jinx", "Kid Flash",
    "Steven Universe", "Garnet", "Amethyst", "Pearl", "Connie", "Lapis Lazuli", "Peridot", "Spinel", "Greg Universe", "Lion",
    "Finn the Human", "Jake the Dog", "Princess Bubblegum", "Marceline the Vampire Queen", "Ice King", "BMO", "Lemongrab", "Flame Princess", "Lady Rainicorn", "Peppermint Butler",
    "Rick Sanchez", "Morty Smith", "Summer Smith", "Beth Smith", "Jerry Smith", "Birdperson", "Mr. Meeseeks", "Evil Morty", "Unity", "Squanchy",
    "Asta", "Yuno", "Noelle Silva", "Mimosa Vermillion", "Luck Voltia", "Magna Swing", "Yami Sukehiro", "Julius Novachrono", "Nacht Faust", "Vanessa Enoteca",
    "Shoyo Hinata", "Tobio Kageyama", "Daichi Sawamura", "Koshi Sugawara", "Asahi Azumane", "Yuu Nishinoya", "Ryunosuke Tanaka", "Kei Tsukishima", "Tadashi Yamaguchi", "Kenma Kozume",
    "Levius Cromwell", "Narumi Katō", "Alice Arisugawa", "Dazai Osamu", "Atsushi Nakajima", "Chuuya Nakahara", "Ranpo Edogawa", "Akutagawa Ryunosuke", "Kunikida Doppo", "Kyoka Izumi",
    "Reigen Arataka", "Ritsu Kageyama", "Teruki Hanazawa", "Dimple", "Toichiro Suzuki", "Sho Suzuki", "Serizawa", "Shigeo Kageyama", "Ekubo",
    "Tomie", "Uzumaki Kirie", "Souichi", "Amigara Fault Victim", "Enigma Boy", "Fuchi", "Kanzaki", "Hideo", "Maruyama", "Miss Fuchi",
    "Endeavor", "Hawks", "Shigaraki", "Dabi", "Toga", "Twice", "Mr. Compress", "Spinner", "Overhaul", "Gentle Criminal",
    "Monkey D. Dragon", "Boa Hancock", "Crocodile", "Donquixote Doflamingo", "Big Mom", "Kaido", "Shanks", "Blackbeard", "Kuzan", "Fujitora",
    "Edward Newgate", "Gol D. Roger", "Silvers Rayleigh", "Buggy the Clown", "Enel", "Bartholomew Kuma", "Sabo", "Koala", "Vivi Nefertari", "Hiyori Kozuki",
    "Usagi Tsukino", "Mamoru Chiba", "Rei Hino", "Ami Mizuno", "Makoto Kino", "Minako Aino", "Setsuna Meioh", "Haruka Tenoh", "Michiru Kaioh", "Hotaru Tomoe",
    "Itachi Uchiha", "Madara Uchiha", "Kakashi Hatake", "Minato Namikaze", "Tsunade", "Jiraiya", "Orochimaru", "Rock Lee", "Might Guy",
    "Gaara", "Temari", "Kankuro", "Hinata Hyuga", "Neji Hyuga", "Shikamaru Nara", "Ino Yamanaka", "Choji Akimichi", "Kiba Inuzuka", "Shino Aburame",
    "Boruto Uzumaki", "Sarada Uchiha", "Mitsuki", "Kawaki", "Sumire Kakei", "Metal Lee", "Denki Kaminarimon", "Iwabe Yuino", "Himawari Uzumaki", "Moegi Kazamatsuri",
    "Edward Cullen", "Bella Swan", "Jacob Black", "Carlisle Cullen", "Alice Cullen", "Jasper Hale", "Rosalie Hale", "Emmett Cullen", "Esme Cullen", "Victoria",
    "Elena Gilbert", "Damon Salvatore", "Stefan Salvatore", "Bonnie Bennett", "Caroline Forbes", "Klaus Mikaelson", "Rebekah Mikaelson", "Elijah Mikaelson", "Alaric Saltzman", "Jeremy Gilbert",
    "Buffy Summers", "Willow Rosenberg", "Xander Harris", "Spike", "Angel", "Giles", "Cordelia Chase", "Faith Lehane", "Tara Maclay", "Anya Jenkins",
    "Twilight Sparkle", "Rainbow Dash", "Fluttershy", "Rarity", "Pinkie Pie", "Applejack", "Spike (MLP)", "Starlight Glimmer", "Sunset Shimmer", "Princess Celestia",
    "Optimus Prime", "Megatron", "Bumblebee", "Starscream", "Soundwave", "Ironhide", "Ratchet", "Shockwave", "Grimlock", "Arcee",
    "Master Chief", "Cortana", "The Arbiter", "Sergeant Johnson", "Captain Keyes", "The Didact", "Atriox", "Escharum", "Lasky", "Blue Team",
    "Ichigo Momomiya", "Mint Aizawa", "Lettuce Midorikawa", "Pudding Fong", "Zakuro Fujiwara", "Ash Ketchum", "Misty", "Brock", "Pikachu", "Team Rocket", "James", "Jessie", "Meowth", "Goh", "Serena",
    "Red (Pokémon)", "Blue (Pokémon)", "Green (Pokémon)", "Silver", "Gold", "Crystal", "May", "Max", "Dawn", "Chloe",
    "Yugi Muto", "Yami Yugi", "Seto Kaiba", "Joey Wheeler", "Tea Gardner", "Tristan Taylor", "Bakura", "Marik", "Dark Magician", "Blue-Eyes White Dragon",
    "Conan Edogawa", "Ran Mouri", "Kogoro Mouri", "Ai Haibara", "Kaito Kid", "Shinichi Kudo", "Emma", "Ray", "Norman", "Isabella",
    "Meliodas", "Elizabeth Liones", "Ban", "Diane", "King", "Gowther", "Merlin", "Escanor", "Zeldris", "Estarossa",
    "Natsu Dragneel", "Lucy Heartfilia", "Gray Fullbuster", "Erza Scarlet", "Happy", "Wendy Marvell", "Jellal Fernandes", "Laxus Dreyar", "Gajeel Redfox", "Mirajane Strauss",
    "Rin Okumura", "Yukio Okumura", "Shura Kirigakure", "Shiemi Moriyama", "Mephisto Pheles", "Amaimon", "Zenitsu Agatsuma", "Inosuke Hashibira","Kanao"
    ],
    "environment": [
    "Ancient forest", "Dense jungle", "Bamboo grove", "Haunted woods", "Misty swamp", "Mangrove forest", "Savanna plains", "Rolling grasslands", "Steppe", "Prairie",
    "Rocky canyon", "Grand canyon", "Cliffside coast", "Mountain peak", "Snowy mountains", "Volcanic mountain", "Crater rim", "Desert canyon", "Mesa desert", "Butte valley",
    "Sandy desert", "Dune sea", "Oasis", "Salt flats", "Badlands", "Scorched desert", "Crystal desert", "Ash desert", "Rocky wasteland", "Fossil desert",
    "Icy tundra", "Frozen wasteland", "Permafrost plain", "Glacial valley", "Ice caves", "Snowstorm plateau", "Polar ice cap", "Frozen fjord", "Iceberg field", "Snowy meadow",
    "Tropical island", "Coral reef", "Lagoon", "Atoll", "Sandy beach", "Rocky beach", "Cliffside coast", "Seaside cave", "Underwater trench", "Sunken city",
    "Cave system", "Crystal cavern", "Glowworm cave", "Lava tubes", "Stalactite cavern", "Stalagmite cavern", "Underground river", "Subterranean lake", "Collapsed mine", "Bat cave",
    "Urban cityscape", "Futuristic megacity", "Cyberpunk alley", "Neon-drenched streets", "Skyscraper rooftops", "Rundown slums", "Underground subway", "Abandoned mall", "Derelict factory", "Construction site",
    "Castle courtyard", "Fortress walls", "Medieval village", "Cobblestone streets", "Ruined cathedral", "Crumbling castle", "Haunted manor", "Ancient monastery", "Gothic tower", "Dungeon corridor",
    "Shipwreck site", "Sunken galleon", "Harbor docks", "Fishing village", "Abandoned shipyard", "Stormy sea", "Pirate cove", "Treasure island", "Whaling station", "Lighthouse cliff",
    "Floating island", "Sky temple", "Cloud city", "Airship dock", "Windmill plains", "Mountain monastery", "Pegasus roost", "Rainbow bridge", "Sky fortress", "Celestial observatory",
    "Volcanic crater", "Magma chamber", "Lava river", "Ash field", "Burned forest", "Fire mountain", "Scorched plains", "Molten lake", "Pyroclastic flow", "Obsidian field",
    "Alien jungle", "Crystal plains", "Mushroom forest", "Giant fungi swamp", "Floating crystal spires", "Bioluminescent meadow", "Alien hive", "Meteor crater", "Asteroid surface", "Space station hangar",
    "Library of eternity", "Ancient archive", "Mystic sanctum", "Wizard’s tower", "Sorcerer’s library", "Enchanted grove", "Stone circle", "Arcane ruins", "Floating runestones", "Crystal altar",
    "Marketplace bazaar", "Festival grounds", "Arena colosseum", "Royal throne room", "Palace gardens", "Grand ballroom", "Banquet hall", "Temple courtyard", "Sacrificial altar", "Oracle’s shrine",
    "Battlefield", "War-torn ruins", "Trenches", "Bombed-out city", "Desert battlefield", "Frozen battlefield", "Ruined fortress", "Ancient battlefield", "Boneyard", "Mass grave",
    "Haunted graveyard", "Cursed mausoleum", "Cemetery", "Catacombs", "Ghoul crypt", "Necropolis", "Forgotten tomb", "Sarcophagus chamber", "Pharaoh’s pyramid", "Burial mound",
    "Space colony", "Martian desert", "Moon crater", "Asteroid mining site", "Alien ruins", "Terraforming base", "Starlit observatory", "Satellite debris field", "Derelict spaceship", "Ringworld",
    "Enchanted waterfall", "Rainbow falls", "Sacred spring", "Glowing pond", "Lotus lake", "Frozen waterfall", "Jade river", "Mystic stream", "Cursed swamp", "Golden pond",
    "Underground bunker", "War shelter", "Vault door", "Fallout shelter", "Nuclear ruins", "Collapsed overpass", "Abandoned subway", "Radiation zone", "Wasteland outpost", "Crumbling highway",
    "Fairy glade", "Mushroom circle", "Pixie grove", "Sprite meadow", "Magical orchard", "Crystal garden", "Enchanted pond", "Will-o’-wisp marsh", "Dryad grove", "Eternal bloom meadow",
    "Mechanical workshop", "Steampunk factory", "Clockwork tower", "Gearworks", "Steam vents", "Boiler room", "Airship hangar", "Mech scrapyard", "Rustyard", "Foundry",
    "Futuristic lab", "Biotech facility", "Cryogenic chamber", "Gene-splicing lab", "Nanotech research wing", "Alien autopsy room", "Energy core chamber", "AI control hub", "Digital arena", "VR battlefield",
    "Stormy cliffs", "Hurricane beach", "Lightning plateau", "Thunder peaks", "Tempest island", "Cyclone plains", "Tornado alley", "Wind-swept ridge", "Howling canyon", "Rain-soaked jungle",
    "Savage jungle ruins", "Temple ruins", "Overgrown ziggurat", "Sunken ruins", "Lost city", "Collapsed aqueduct", "Jungle pyramid", "Ancient observatory", "Stone giants’ causeway", "Desert obelisk",
    "Frozen castle", "Ice palace", "Snowbound village", "Winter market", "Glacial fortress", "Frozen canyon", "Crystal ice cave", "Aurora-lit tundra", "Snowstorm ruins", "Frost giant lair",
    "Volcanic temple", "Ashen ziggurat", "Fire giant fortress", "Molten citadel", "Infernal altar", "Lava throne room", "Burning cathedral", "Obsidian spire", "Hell gate", "Demon pit",
    "Ocean abyss", "Deep trench", "Sunken reef", "Undersea palace", "Coral kingdom", "Seaweed forest", "Shark-infested waters", "Whale graveyard", "Sunken temple", "Abyssal vents",
    "Urban rooftop", "City park", "Subway tunnels", "Rooftop garden", "Fountain plaza", "Shopping district", "Tech market", "Corporate skyscraper", "Neon freeway", "Hologram square",
    "Wilderness cabin", "Hunting lodge", "Mountain trail", "River crossing", "Forest camp", "Desert campfire", "Nomad tent", "Oasis encampment", "Snowy cabin", "Fishing hut"
    ],
    creature: [
    "Dragon", "Wyvern", "Hydra", "Griffin", "Phoenix", "Basilisk", "Cockatrice", "Chimera", "Manticore", "Sphinx",
    "Unicorn", "Pegasus", "Kraken", "Leviathan", "Sea Serpent", "Mermaid", "Siren", "Kelpie", "Selkie", "Nymph",
    "Dryad", "Satyr", "Centaur", "Minotaur", "Cyclops", "Gorgon", "Medusa", "Harpy", "Lamia", "Echidna",
    "Cerberus", "Hellhound", "Imp", "Demon", "Archdemon", "Fallen Angel", "Angel", "Seraphim", "Cherubim", "Nephilim",
    "Djinn", "Efreet", "Ifrit", "Marid", "Ghoul", "Zombie", "Skeleton", "Wight", "Wraith", "Specter",
    "Phantom", "Ghost", "Poltergeist", "Banshee", "Revenant", "Vampire", "Nosferatu", "Dhampir", "Werewolf", "Lycanthrope",
    "Wendigo", "Skinwalker", "Chupacabra", "Mothman", "Bigfoot", "Yeti", "Sasquatch", "Loch Ness Monster", "Thunderbird", "Pukwudgie",
    "Kappa", "Oni", "Tengu", "Kitsune", "Tanuki", "Yokai", "Jorogumo", "Noppera-bo", "Yurei", "Bake-danuki",
    "Rakshasa", "Asura", "Naga", "Garuda", "Yaksha", "Bhuta", "Vetala", "Pisacha", "Preta", "Manananggal",
    "Tikbalang", "Kapre", "Diwata", "Anito", "Duwende", "Bakunawa", "Sigbin", "Engkanto", "Aswang", "Penanggalan",
    "Pontianak", "Langsuir", "Toyol", "Bhoot", "Churel", "Jinn", "Shaitan", "Angel of Death", "Death Knight", "Lich",
    "Necromancer’s Familiar", "Bone Dragon", "Corpse Giant", "Plague Rat", "Blight Serpent", "Carrion Crow", "Shadow Fiend", "Void Spawn", "Eldritch Horror", "Shoggoth",
    "Deep One", "Star Spawn", "Mi-Go", "Yithian", "Nightgaunt", "Dark Young", "Hastur Spawn", "Nyarlathotep Avatar", "Cthulhu Spawn", "Azathoth Fragment",
    "Fomorian", "Bansidhe", "Cailleach", "Firbolg", "Tuatha De Danann", "Bean Nighe", "Selkie Queen", "Morrigan", "Dagda’s Hound", "Balor",
    "Fae", "Fairy", "Pixie", "Sprite", "Brownie", "Boggan", "Redcap", "Hobgoblin", "Gremlin", "Goblin",
    "Orc", "Troll", "Ogre", "Hag", "Bugbear", "Gnoll", "Kobold", "Hob", "Changeling", "Elf",
    "Dark Elf", "High Elf", "Wood Elf", "Sea Elf", "Frost Elf", "Fire Elf", "Moon Elf", "Sun Elf", "Shadow Elf", "Blood Elf",
    "Dwarf", "Duergar", "Gnome", "Halfling", "Hobbit", "Ent", "Treefolk", "Treant", "Sapling Guardian", "Living Statue",
    "Golem", "Clay Golem", "Stone Golem", "Iron Golem", "Flesh Golem", "Crystal Golem", "Obsidian Golem", "Bone Golem", "Wood Golem", "Sand Golem",
    "Elemental", "Fire Elemental", "Water Elemental", "Air Elemental", "Earth Elemental", "Lightning Elemental", "Ice Elemental", "Shadow Elemental", "Light Elemental", "Void Elemental",
    "Salamander", "Sylph", "Undine", "Gnome (Elemental)", "Djinn Elemental", "Storm Spirit", "Inferno Wraith", "Frost Wraith", "Ember Spirit", "Tempest Spirit",
    "Behemoth", "Leviathan Serpent", "World Turtle", "Cosmic Whale", "Celestial Lion", "Astral Serpent", "Solar Phoenix", "Lunar Stag", "Stellar Dragon", "Comet Beast",
    "Chthonic Worm", "Pit Serpent", "Abyssal Leviathan", "Hell Serpent", "Void Drake", "Chaos Spawn", "Warp Beast", "Entropy Hound", "Time Eater", "Chrono Serpent",
    "Mechanical Dragon", "Clockwork Spider", "Automaton", "Steel Serpent", "Gear Golem", "Arcane Construct", "Soulforged Automaton", "Runic Sentinel", "Obsidian Automaton", "Crystal Construct",
    "Alien", "Xenomorph", "Predator Beast", "Parasite Queen", "Hive Tyrant", "Brood Mother", "Drone Swarm", "Insectoid Soldier", "Mantid Warrior", "Antlion King",
    "Scorpion Lord", "Sand Worm", "Desert Serpent", "Cactus Beast", "Glass Spider", "Ash Drake", "Magma Serpent", "Volcano Golem", "Molten Hound", "Obsidian Drake",
    "Ice Drake", "Frost Giant", "Yeti Lord", "Snow Serpent", "Ice Phoenix", "Aurora Spirit", "Blizzard Wraith", "Frost Wyrm", "Winter Wolf", "Glacier Golem",
    "Thunder Serpent", "Storm Drake", "Lightning Wolf", "Tempest Golem", "Sky Whale", "Cloud Serpent", "Storm Roc", "Hurricane Spirit", "Rain Bringer", "Thunder Titan",
    "Forest Guardian", "Moss Golem", "Rooted Horror", "Swamp Thing", "Bog Serpent", "Fenrir", "Dire Wolf", "Great Stag", "Forest Dragon", "Ancient Treant",
    "Corrupted Treant", "Rotting Ent", "Swamp Hag", "Will-o’-the-Wisp", "Marsh Spirit", "Bog Wraith", "Poison Serpent", "Venom Hydra", "Toxic Drake", "Plague Elemental",
    "Sandstorm Djinn", "Desert Roc", "Mirage Serpent", "Scarab Lord", "Anubis Warrior", "Mummy", "Pharaoh Shade", "Sphinx of Secrets", "Cobra Guardian", "Jackal Beast",
    "Blood Serpent", "Vampire Bat", "Blood Wraith", "Crimson Drake", "Bone Serpent", "Graveyard Horror", "Ghast", "Shade", "Crypt Guardian", "Night Terror",
    "Celestial Serpent", "Heavenly Stag", "Starlight Phoenix", "Radiant Lion", "Solar Serpent", "Galactic Drake", "Comet Spirit", "Eclipse Serpent", "Nebula Beast", "Cosmos Whale",
    "Time Wraith", "Temporal Serpent", "Chrono Drake", "Aeon Serpent", "Infinity Worm", "Void Horror", "Eternal Phoenix", "Immortal Serpent", "Undying Dragon", "Endless Golem",
    "Mechanical Wyrm", "Runesteel Dragon", "Technomancer’s Construct", "Cybernetic Chimera", "Mech Serpent", "Nano Swarm", "Digital Ghost", "AI Construct", "Holographic Beast", "Virtual Dragon",
    "Bone Colossus", "Skull Serpent", "Wraith Dragon", "Crypt Golem", "Necrotic Phoenix", "Phantom Wolf", "Spectral Lion", "Ethereal Stag", "Spirit Dragon", "Shadow Serpent",
    "Dark Drake", "Abyss Worm", "Nether Wraith", "Umbral Horror", "Oblivion Spawn", "Dusk Wolf", "Midnight Serpent", "Cloaked Phantom", "Nightshade Beast", "Ebon Drake",
    "Ash Wraith", "Cinder Drake", "Flame Elemental", "Infernal Phoenix", "Lava Serpent", "Pyre Golem", "Burning Horror", "Molten Colossus", "Hellfire Wyrm", "Demon Drake",
    "Tidal Serpent", "Abyssal Whale", "Sea Drake", "Deep Sea Horror", "Coral Golem", "Tide Spirit", "Kraken Spawn", "Leviathan Child", "Siren Queen", "Ocean Phantom",
    "Saltwater Specter", "Whirlpool Serpent", "Maelstrom Horror", "Wave Elemental", "Water Drake", "Marine Chimera", "Abyssal Guardian", "Shark Beast", "Hammerhead Horror", "Piranha Swarm",
    "Angler Demon", "Lamprey Horror", "Tentacle Beast", "Cuttlefiend", "Jellyfish Horror", "Electric Eel Serpent", "Corrupted Mermaid", "Barnacle Golem", "Seaweed Horror", "Sunken Wraith",
    "Frost Hag", "Ice Witch", "Snow Wight", "Arctic Serpent", "Glacial Horror", "Polar Bear Beast", "Frost Troll", "Snow Yeti", "Aurora Serpent", "Frozen Phoenix",
    "Crystal Serpent", "Gem Golem", "Amethyst Drake", "Emerald Serpent", "Ruby Dragon", "Sapphire Serpent", "Diamond Drake", "Obsidian Horror", "Quartz Wraith", "Topaz Beast",
    "Prism Serpent", "Opal Chimera", "Moonstone Dragon", "Sunstone Drake", "Celestite Horror", "Meteor Beast", "Comet Serpent", "Stardust Drake", "Galaxy Horror", "Solar Dragon",
    "Lunar Chimera", "Eclipse Drake", "Starspawn Horror", "Cosmic Entity", "Nebula Phoenix", "Wormhole Serpent", "Asteroid Golem", "Black Hole Beast", "Pulsar Horror", "Quasar Drake",
    "Forest Nymph", "Woodland Spirit", "Sylvan Beast", "Deer Guardian", "Forest Serpent", "Root Serpent", "Tree Horror", "Vine Wraith", "Bark Golem", "Leaf Sprite",
    "Moss Horror", "Swamp Serpent", "Bog Giant", "Fen Beast", "Rot Wraith", "Decay Horror", "Slime Monster", "Ooze Horror", "Gelatinous Cube", "Amorphous Horror",
    "Acid Slime", "Toxic Ooze", "Radioactive Horror", "Sludge Serpent", "Waste Beast", "Pollution Drake", "Venomous Ooze", "Corrosive Horror", "Acid Drake", "Biohazard Golem",
    "Scarab Beast", "Locust Swarm", "Beetle Horror", "Ant Queen", "Spider Demon", "Widow Horror", "Web Serpent", "Scorpion Horror", "Centipede Beast", "Millipede Horror",
    "Worm Horror", "Leech Serpent", "Flesh Worm", "Carrion Horror", "Bone Worm", "Parasite Beast", "Hive Mind Horror", "Infestation Horror", "Insect Chimera", "Bug Colossus",
    "Grave Horror", "Tomb Wraith", "Crypt Serpent", "Catacomb Horror", "Ghoul Lord", "Necrotic Beast", "Pale Rider", "Death Serpent", "Funeral Wraith", "Sepulcher Horror",
    "Sky Serpent", "Air Drake", "Wind Elemental", "Storm Horror", "Hurricane Beast", "Typhoon Serpent", "Cyclone Horror", "Tempest Drake", "Cloud Chimera", "Sky Golem",
    "Lightning Serpent", "Thunder Beast", "Storm Colossus", "Electric Horror", "Bolt Drake", "Voltage Horror", "Static Serpent", "Surge Wraith", "Plasma Horror", "Spark Sprite",
    "Solar Horror", "Radiant Beast", "Luminous Dragon", "Aurora Chimera", "Halo Serpent", "Starfire Horror", "Sun Drake", "Solar Wraith", "Stellar Horror", "Celestial Beast",
    "Moon Horror", "Lunar Wraith", "Eclipse Horror", "Night Serpent", "Dream Wraith", "Illusion Beast", "Mirage Horror", "Hallucination Serpent", "Mind Horror", "Psychic Drake",
    "Telepathic Beast", "Clairvoyant Horror", "Vision Serpent", "Dream Serpent", "Sleep Wraith", "Insomnia Horror", "Nightmare Beast", "Phobia Horror", "Terror Chimera", "Fear Drake",
    "Gremlin King", "Trickster Sprite", "Mischief Demon", "Prankster Spirit", "Shadow Imp", "Illusionist Horror", "Mask Wraith", "Trick Horror", "Fool’s Phantom", "Laughing Demon",
    "Clown Horror", "Carnival Beast", "Toy Horror", "Marionette Demon", "Doll Horror", "Puppet Serpent", "String Wraith", "Clockwork Horror", "Mechanical Beast", "Gear Horror",
    "Cyber Drake", "Nano Serpent", "Virtual Beast", "Data Ghost", "Code Wraith", "Digital Horror", "Hologram Serpent", "VR Chimera", "AI Horror", "Technobeast",
    "Steam Golem", "Gearwork Horror", "Cog Serpent", "Iron Drake", "Rust Horror", "Corroded Golem", "Industrial Beast", "Machine Horror", "Foundry Golem", "Forge Serpent",
    "Astral Horror", "Ethereal Beast", "Dimension Serpent", "Multiverse Drake", "Portal Horror", "Gate Wraith", "Interdimensional Beast", "Warp Horror", "Void Serpent", "Chaos Drake",
    "Entropy Horror", "Order Serpent", "Balance Wraith", "Fate Beast", "Destiny Horror", "Prophecy Serpent", "Oracle Wraith", "Seer Beast", "Vision Horror", "Future Drake",
    "Past Serpent", "Time Horror", "Clockwork Serpent", "Hourglass Beast", "Eon Horror", "Chrono Drake", "Temporal Wraith", "Infinity Serpent", "Timeless Beast", "Eternal Horror",
    "Martian Beast", "Alien Serpent", "Extraterrestrial Drake", "Galactic Horror", "Cosmic Parasite", "Asteroid Worm", "Space Kraken", "Moon Beast", "Planet Horror", "Star Serpent",
    "Black Hole Drake", "Nebula Horror", "Supernova Serpent", "Quasar Beast", "Wormhole Horror", "Solar Flare Dragon", "Comet Chimera", "Dark Matter Horror", "Gravity Serpent", "Celestial Horror",
    "Hydra Spawn", "Twin-Headed Serpent", "Three-Headed Dragon", "Multi-Eyed Horror", "Tentacle Serpent", "Winged Worm", "Horned Beast", "Spined Horror", "Armored Drake", "Scaled Serpent",
    "Feathered Serpent", "Plumed Serpent", "Quetzalcoatl", "Jade Dragon", "Serpent God", "Winged Chimera", "Winged Drake", "Aerial Horror", "Sky Phantom", "Cloud Horror",
    "Sun Serpent", "Moon Serpent", "Star Serpent", "Galaxy Serpent", "Universe Beast", "Creation Horror", "Destruction Serpent", "Life Serpent", "Death Serpent", "Rebirth Phoenix",
    "Ash Phoenix", "Cinder Serpent", "Inferno Chimera", "Burnt Horror", "Smoldering Wraith", "Lava Colossus", "Magma Serpent", "Scorch Drake", "Ember Beast", "Blazing Horror",
    "Charred Golem", "Pyro Horror", "Volcanic Serpent", "Molten Horror", "Soot Wraith", "Ignition Beast", "Kindling Horror", "Spark Serpent", "Torch Dragon", "Wildfire Beast",
    "Ocean Leviathan", "Tidal Colossus", "Current Serpent", "Deepwater Horror", "Kraken Horror", "Whirlpool Beast", "Maelstrom Drake", "Riptide Horror", "Surge Serpent", "Wave Horror",
    "Coral Horror", "Shell Golem", "Barnacle Beast", "Nautilus Horror", "Trench Horror", "Seabed Wraith", "Fathom Horror", "Sunken Serpent", "Anchor Horror", "Mariner Beast",
    "Frozen Horror", "Glacier Colossus", "Permafrost Serpent", "Ice Chimera", "Avalanche Horror", "Snow Beast", "Frostbite Wraith", "Icicle Horror", "Blizzard Drake", "Tundra Horror",
    "Aurora Beast", "Winter Serpent", "Snowstorm Horror", "Shiver Wraith", "Frostbound Horror", "Cryo Chimera", "Arctic Horror", "Subzero Beast", "Frozen Titan", "Polar Horror",
    "Crystal Horror", "Gem Beast", "Amethyst Horror", "Emerald Horror", "Ruby Horror", "Sapphire Horror", "Diamond Horror", "Obsidian Serpent", "Quartz Horror", "Topaz Horror",
    "Prism Horror", "Opal Horror", "Moonstone Horror", "Sunstone Horror", "Celestite Beast", "Meteor Horror", "Comet Horror", "Stardust Horror", "Solar Horror", "Lunar Horror",
    "Eclipse Beast", "Nebula Horror", "Galaxy Beast", "Cosmic Horror", "Astral Horror", "Stellar Serpent", "Planet Beast", "Wormhole Horror", "Black Hole Horror", "Pulsar Beast",
    "Forest Horror", "Woodland Beast", "Sylvan Horror", "Deer Horror", "Tree Horror", "Vine Horror", "Bark Horror", "Leaf Horror", "Moss Horror", "Root Horror",
    "Swamp Horror", "Bog Horror", "Fen Horror", "Rot Horror", "Decay Horror", "Slime Horror", "Ooze Horror", "Gel Horror", "Acid Horror", "Toxic Horror",
    "Scarab Horror", "Locust Horror", "Beetle Horror", "Ant Horror", "Spider Horror", "Scorpion Horror", "Centipede Horror", "Millipede Horror", "Worm Horror", "Leech Horror",
    "Parasite Horror", "Hive Horror", "Insect Horror", "Bug Horror", "Carrion Horror", "Flesh Horror", "Bone Horror", "Ghoul Horror", "Necrotic Horror", "Undead Horror",
    "Grave Beast", "Tomb Horror", "Crypt Horror", "Catacomb Horror", "Ghast Horror", "Phantom Horror", "Specter Horror", "Wight Horror", "Shade Horror", "Death Horror",
    "Sky Horror", "Air Horror", "Wind Horror", "Storm Horror", "Hurricane Horror", "Cyclone Horror", "Tempest Horror", "Cloud Horror", "Lightning Horror", "Thunder Horror",
    "Electric Horror", "Bolt Horror", "Voltage Horror", "Static Horror", "Plasma Horror", "Surge Horror", "Shock Horror", "Electro Horror", "Storm Wraith", "Sky Wraith",
    "Radiant Horror", "Luminous Horror", "Light Horror", "Halo Horror", "Sun Horror", "Celestial Horror", "Star Horror", "Moon Horror", "Dawn Horror", "Dusk Horror",
    "Eclipse Horror", "Dream Horror", "Illusion Horror", "Mirage Horror", "Hallucination Horror", "Vision Horror", "Mind Horror", "Psychic Horror", "Telepathic Horror", "Clairvoyant Horror",
    "Future Horror", "Past Horror", "Time Horror", "Clockwork Horror", "Hourglass Horror", "Chrono Horror", "Temporal Horror", "Infinity Horror", "Eternal Horror", "Timeless Horror",
    "Gremlin Horror", "Imp Horror", "Trickster Horror", "Prankster Horror", "Mask Horror", "Laughing Horror", "Clown Horror", "Carnival Horror", "Toy Horror", "Doll Horror",
    "Puppet Horror", "String Horror", "Marionette Horror", "Clockwork Beast", "Mechanical Horror", "Gear Horror", "Cog Horror", "Rust Horror", "Iron Horror", "Steel Horror",
    "Nano Horror", "Virtual Horror", "Data Horror", "Code Horror", "Digital Horror", "Hologram Horror", "AI Horror", "Technobeast Horror", "Cyber Horror", "Machine Horror",
    "Steam Horror", "Industrial Horror", "Foundry Horror", "Forge Horror", "Factory Horror", "Gearwork Horror", "Automaton Horror", "Ironclad Horror", "Copper Horror", "Bronze Horror",
    "Astral Beast", "Ethereal Horror", "Dimension Horror", "Portal Horror", "Interdimensional Horror", "Warp Horror", "Void Horror", "Chaos Horror", "Entropy Horror", "Order Horror",
    "Balance Horror", "Fate Horror", "Destiny Horror", "Prophecy Horror", "Oracle Horror", "Seer Horror", "Vision Beast", "Illusion Beast", "Dream Beast", "Nightmare Horror",
    "Phobia Horror", "Terror Horror", "Fear Horror", "Insanity Horror", "Madness Horror", "Delusion Horror", "Paranoia Horror", "Hysteria Horror", "Anxiety Horror", "Dread Horror",
    "Martian Horror", "Alien Horror", "Extraterrestrial Horror", "Galactic Horror", "Cosmic Parasite", "Asteroid Horror", "Space Horror", "Moon Horror", "Planet Horror", "Star Horror",
    "Supernova Horror", "Quasar Horror", "Solar Flare Horror", "Comet Horror", "Dark Matter Horror", "Gravity Horror", "Celestial Horror", "Stellar Horror", "Nebula Horror", "Universe Horror",
    "Hydra Horror", "Twin-Headed Horror", "Three-Headed Horror", "Multi-Eyed Horror", "Tentacle Horror", "Winged Horror", "Horned Horror", "Spined Horror", "Armored Horror", "Scaled Horror",
    "Feathered Horror", "Plumed Horror", "Quetzal Horror", "Serpent God Horror", "Winged Chimera", "Winged Drake", "Flying Horror", "Soaring Horror", "Aerial Horror", "Sky Horror",
    "Sun Horror", "Moon Horror", "Star Horror", "Galaxy Horror", "Universe Horror", "Creation Horror", "Destruction Horror", "Life Horror", "Death Horror", "Rebirth Horror",
    "Ashen Wyrm", "Charcoal Horror", "Cinder Drake", "Infernal Phoenix", "Burning Colossus", "Hell Serpent", "Ash Fiend", "Scorching Wraith", "Blister Beast", "Charred Titan",
    "Molten Chimera", "Volcano Horror", "Pyre Drake", "Soot Serpent", "Ember Titan", "Inferno Horror", "Flare Beast", "Torch Horror", "Wildfire Titan", "Blaze Horror",
    "Abyss Horror", "Deepsea Horror", "Tide Horror", "Trench Colossus", "Mariana Horror", "Kraken Titan", "Leviathan Horror", "Surge Colossus", "Maelstrom Horror", "Nautical Horror",
    "Frozen Colossus", "Glacial Horror", "Snow Titan", "Ice Horror", "Polar Horror", "Arctic Titan", "Cryo Horror", "Avalanche Beast", "Blizzard Horror", "Winter Horror",
    "Crystal Colossus", "Diamond Titan", "Ruby Beast", "Emerald Colossus", "Sapphire Horror", "Obsidian Beast", "Quartz Titan", "Amethyst Horror", "Gem Horror", "Topaz Beast",
    "Star Colossus", "Lunar Horror", "Solar Colossus", "Cosmic Titan", "Stellar Horror", "Nebula Titan", "Galaxy Horror", "Astral Titan", "Void Colossus", "Eclipse Horror",
    "Forest Colossus", "Sylvan Horror", "Wood Colossus", "Tree Horror", "Vine Titan", "Moss Horror", "Bark Titan", "Root Horror", "Flora Horror", "Jungle Colossus",
    "Swamp Colossus", "Bog Titan", "Fen Horror", "Rot Titan", "Decay Colossus", "Toxic Horror", "Poison Colossus", "Slime Titan", "Ooze Horror", "Mire Horror",
    "Scarab Titan", "Locust Colossus", "Beetle Horror", "Insect Titan", "Arachnid Horror", "Spider Titan", "Scorpion Horror", "Centipede Titan", "Worm Horror", "Leech Colossus",
    "Undead Colossus", "Ghoul Horror", "Necrotic Titan", "Wight Horror", "Phantom Titan", "Specter Horror", "Grave Colossus", "Crypt Horror", "Tomb Titan", "Death Colossus",
    "Storm Colossus", "Hurricane Horror", "Cyclone Colossus", "Tempest Horror", "Thunder Titan", "Lightning Colossus", "Electric Horror", "Voltage Titan", "Plasma Horror", "Shock Colossus",
    "Radiant Colossus", "Light Horror", "Halo Titan", "Luminous Horror", "Sun Colossus", "Celestial Horror", "Moon Colossus", "Starlight Horror", "Dawn Colossus", "Twilight Horror",
    "Dream Colossus", "Illusion Horror", "Vision Titan", "Hallucination Horror", "Mirage Colossus", "Mind Horror", "Psychic Colossus", "Telepathic Horror", "Oracle Titan", "Prophecy Horror",
    "Time Colossus", "Chrono Horror", "Temporal Titan", "Hourglass Horror", "Clockwork Titan", "Infinity Horror", "Timeless Titan", "Eternal Horror", "Past Horror", "Future Horror",
    "Gremlin Titan", "Imp Horror", "Trickster Titan", "Mask Horror", "Jester Colossus", "Clown Horror", "Toy Titan", "Doll Horror", "Puppet Titan", "Marionette Horror",
    "Mechanical Titan", "Gear Horror", "Cog Colossus", "Rust Horror", "Iron Titan", "Steel Horror", "Automaton Colossus", "Copper Horror", "Bronze Titan", "Clockwork Horror",
    "Nano Colossus", "Digital Horror", "Virtual Titan", "Data Horror", "Code Titan", "AI Horror", "Cyber Colossus", "Machine Horror", "Technobeast Titan", "Hologram Horror",
    "Steam Titan", "Industrial Horror", "Foundry Colossus", "Forge Horror", "Factory Titan", "Gearwork Horror", "Automaton Titan", "Ironclad Horror", "Smokestack Titan", "Engine Horror",
    "Astral Colossus", "Ethereal Horror", "Dimension Titan", "Portal Horror", "Warp Titan", "Void Horror", "Chaos Colossus", "Entropy Horror", "Balance Titan", "Order Horror",
    "Fate Colossus", "Destiny Horror", "Seer Titan", "Prophecy Horror", "Vision Colossus", "Dream Horror", "Illusion Colossus", "Nightmare Horror", "Fear Titan", "Phobia Horror",
    "Martian Colossus", "Alien Horror", "Extraterrestrial Titan", "Space Horror", "Cosmic Colossus", "Planet Horror", "Stellar Colossus", "Asteroid Horror", "Comet Colossus", "Galaxy Horror",
    "Hydra Titan", "Twin-Headed Horror", "Three-Headed Titan", "Multi-Eyed Horror", "Tentacle Titan", "Winged Horror", "Horned Titan", "Spined Horror", "Armored Titan", "Scaled Horror",
    "Feathered Titan", "Plumed Horror", "Winged Colossus", "Soaring Horror", "Aerial Colossus", "Flying Horror", "Sky Titan", "Storm Horror", "Sun Colossus", "Moon Horror",
    "Creation Titan", "Destruction Horror", "Life Titan", "Death Horror", "Rebirth Colossus", "Cycle Horror", "Origin Colossus", "End Horror", "Eternal Titan", "Immortal Horror"
  
    ]
    
  };

  const category = req.query.category;

if (!category || !prompts[category]) {
 res.status(400).json({ error: "Invalid category" });
 return;
}

const rand = prompts[category][Math.floor(Math.random() * prompts[category].length)];
res.status(200).json({ prompt: rand });
}
